#+OPTIONS: ^:{}
#+STARTUP: indent nolineimages overview num
#+TITLE: Hyper Card system for Ruby
#+AUTHOR: Shigeto R. Nishitani
#+EMAIL:     (concat "shigeto_nishitani@mac.com")
#+LANGUAGE:  jp
#+OPTIONS:   H:4 toc:t num:2
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup


* HyperCard

Hyper Card system for Ruby learners and users

HyperCard is originally released in the late 80's 
by Apple with the Macintosh SE, made by Bill Atkinson.
After that, although the concept of HyperCard has been used
in MacOS, Finder, Keynote and so on,
the simple application of HyperCard has gone.
This HyperCard system try to rebuild the hyper card world again.

Rubyを習得する人あるいは使う人のためのHyper Cardシステムです．
Hyper CardはAppleのMacのためにBill Atkinsonが開発した付録でした．
その後，HyperCardの思想は，MacOS(Finder), あるいはKeynoteに
受け継がれたのですが，HyperCard自身はどっかへ消えていきました．
何かプログラミング言語を習得するには，
写経しろとか，数学の問題を解くようにとか言われますが，
現代の初心者にはなんのこっちゃだと思います．
あるいはコピペと写経の違いが何かや，
チャンキングとカプセル化や，隠蔽とトグル表示が何かも，
クラス化(オブジェクト指向)を
実感できてない人には，ピンと来てないんでしょう．
そんな人でも，
Rubyを「忘れず」（記憶することではなく），
codingできるようなシステムを目指します．

梅棹忠夫の「知的生産の技術」で紹介されている
京大カードシステムの中に，そのヒントがあるように思います．

同じところと違うところ？

* Installation

TODO: Replace `UPDATE_WITH_YOUR_GEM_NAME_IMMEDIATELY_AFTER_RELEASE_TO_RUBYGEMS_ORG` with your gem name right after releasing it to RubyGems.org. Please do not do it earlier due to security reasons. Alternatively, replace this section with instructions to install your gem from git if you don't plan to release to RubyGems.org.

Install the gem and add to the application's Gemfile by executing:

    $ bundle add UPDATE_WITH_YOUR_GEM_NAME_IMMEDIATELY_AFTER_RELEASE_TO_RUBYGEMS_ORG

If bundler is not being used to manage dependencies, install the gem by executing:

    $ gem install UPDATE_WITH_YOUR_GEM_NAME_IMMEDIATELY_AFTER_RELEASE_TO_RUBYGEMS_ORG

* Usage

TODO: Write usage instructions here

* Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake test-unit` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and the created tag, and push the `.gem` file to [rubygems.org](https://rubygems.org).

* Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/[USERNAME]/hyper_card. This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the [code of conduct](https://github.com/[USERNAME]/hyper_card/blob/main/CODE_OF_CONDUCT.md).

* License

The gem is available as open source under the terms of the [MIT License](https://opensource.org/licenses/MIT).

## Code of Conduct

Everyone interacting in the HyperCard project's codebases, issue trackers, chat rooms and mailing lists is expected to follow the [code of conduct](https://github.com/[USERNAME]/hyper_card/blob/main/CODE_OF_CONDUCT.md).

