#+OPTIONS: ^:{}
#+STARTUP: indent nolineimages overview num
#+TITLE: パラノ的感性とスキゾ的感性
#+AUTHOR: 哲学の練習帳
#+LANGUAGE:  jp
#+OPTIONS:   H:4 toc:t num:2
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

https://note.com/kagurakanon/n/n3fd6e1f989ee



296
哲学の練習帳
2020年1月30日 21:58

* 「パラノ」と「スキゾ」

「パラノ」と「スキゾ」というかつて一斉を風靡した言葉あります。この用語は、ジル・ドゥルーズとフェリックス・ガタリの共著「アンチ・オイエディプス」のなかで用いられ、これをバブル直前の1984年、浅田彰氏が「逃走論」の中で紹介したことがきっかけで、やたらと流行りだし、その年の流行語大賞の銅賞にも選ばれました。

ドゥルーズらの思想は1980代のニューアカデミズムの文脈で当時の消費社会肯定論として受容されましたが、現代においてはまた少し違う意味でスキゾ的な感性が必要とされているでしょう。

* 偏執と分裂

パラノもスキゾも元々は精神医学に由来する用語であり、「パラノ」はパラノイア＝偏執型を指し、「スキゾ」とはスキゾフレニア＝分裂型を指しています。

ではパラノは何に「偏執」するのでしょうか？それは端的にいえば「私はこういう人間である」という「アイデンティティ」ということになります。これに対して、スキゾは何に「分裂」するのかというと、こちらもまた「アイデンティティ」ということになります。

パラノ型の人は「何々大学を出て何々会社に就職」という過去の経歴や「会社では部長、家庭では良き夫、良き父親」という現在の社会的役割といった自らのアイデンティティとなるべく整合的な行動を取ろうとします。これはある意味で一貫性のあるわかりやすい人ということになります。

一方でスキゾ型の人はこれまでのアイデンティティにこだわる事なく、その時々の直感や嗅覚に従って自由奔放に行動していきます。これはある意味で予測不能なわかりにくい人という事になります。

* ツリーとリゾーム

ドゥルーズはもともと数学における微分の概念を応用して「差異」の研究をした哲学者ですが、この「パラノとスキゾ」という対比を数学的なニュアンスで表現すれば「パラノ」は積分で「スキゾ」は微分ということになります。

またドゥウーズは「千のプラトー」において西洋哲学が長らくベースにしたある起点を基にしてそこから枝葉を整合的に広げていくような構造を「ツリー」と言い、これに対して特定の起点を持たず無秩序に拡散していく様相を「リゾーム」と名付けました。このツリーにパラノは、リゾームにスキゾがそれぞれ対応するわけです。

この点、浅田氏は「パラノ型」を「住むヒト」と定義し「スキゾ型」を「逃げる人」と定義しました。すなわち張り巡らされたリゾームの中を縦横無尽に逃走するイメージです。

ここで重要なのは事態の変化を捉える鋭い嗅覚とこれまでの蓄積をあっさり放棄できるいさぎよさです。

スキゾ型はともすれば軟弱とか軽薄とかいったイメージで捉えられがちですが、こうしてみればむしろ、しなやかな感性と決断力を持った人と言えるでしょう。

* スキゾ化する現代社会

現代はますますパラノ的な感性だけでは生きづらい時代になって来ていると言えるわけです。

一方で旧来の終身雇用や年功序列に支えられてきた「幸福のロールモデル」が崩壊し、他方で情報化、グローバル化、ポストモダン化が加速する中で、これまで個人がたゆまぬ努力で誠実に積み上げてきたキャリアやスキルが秒速でゴミ屑同然になることも普通にあったりするわけです。

こうした変化の激しい時代においてはスキゾ的な感性と決断力がますます優位になっているといえます。

こうしてみると今の時代は、パラノ的な感性からすると生きづらい時代ですが、スキゾ的な感性にとってはむしろ面白い時代と言えるかもしれません。


